
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Iago Rossi
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    private Connection c;
    public CRUD mysql;

    
    
    public Cadastro() {
        initComponents();
       mysql = new CRUD();
       c = mysql.connect
          ("com.mysql.jdbc.Driver","ufnprojetomove","USc5KrG_77nwVC","jdbc:mysql://ufnprojetomove.mysql.dbaas.com.br:3306/ufnprojetomove?useTimeZone=true&serverTimezone=UTC&user=");
      
               
                   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
      public void Gravar() {
      
        CRUD crud = new CRUD();
            
        Funcionario funcionario = new Funcionario();
    
            

        if (jRadioAdm.isSelected()) {
            funcionario.setTipoFuncionario("Funcionario Administrador ");
        }
        if (jRadioFinanceiro.isSelected()) {
            funcionario.setTipoFuncionario("Funcionario de Financeiro");
        }
        
        if (jRadioProducao.isSelected()) {
            funcionario.setTipoFuncionario("Funcionario de Produção");
        }
        if (jRadioFuncionario.isSelected()) {
            funcionario.setTipoFuncionario("Funcionario");
            
        }
         String query = "INSERT INTO Funcionario (NOME, EMAIL,SENHA , CPF, TELEFONE, DATA_NASC, TIPO_FUNCIONARIO) "
                + "values '" + jTFNome.getText() + "', '" + jTFEmail.getText() + "', '" + jTFSenha.getText()
                + "', '" + jTFCpf.getText() + "', '" + jTFTelefone.getText() + "', '" + jTFDataNasc.getText() + "','" + jTFEndereco.getText()+"', '" + "1" + "')";
       
           
        
       
       crud.connect();
       
       
               
            
        }
      
       private void limparCampos(){
        jTFNome.setText("");
        jTFEmail.setText("");
        jTFSenha.setText ("");
        jTFCpf.setText("");
        jTFTelefone.setText("");
        jTFDataNasc.setText("");
        jTFEndereco.setText("");
        buttonGroup1.clearSelection();
           
            
        }
            
       
       
   
                   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        JlabelDataNasc = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelTipoFunncionario = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFEmail = new javax.swing.JTextField();
        jTFSenha = new javax.swing.JTextField();
        jTFCpf = new javax.swing.JTextField();
        jTFTelefone = new javax.swing.JTextField();
        jTFDataNasc = new javax.swing.JTextField();
        jTFEndereco = new javax.swing.JTextField();
        jRadioAdm = new javax.swing.JRadioButton();
        jRadioFinanceiro = new javax.swing.JRadioButton();
        jRadioProducao = new javax.swing.JRadioButton();
        jRadioFuncionario = new javax.swing.JRadioButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Funcionários");

        jLabelNome.setText("Nome");

        jLabelEmail.setText("Email");

        jLabelSenha.setText("Senha");

        jLabelCpf.setText("CPF");

        jLabelTelefone.setText("Telefone");

        JlabelDataNasc.setText("Data de Nacimento");

        jLabelEndereco.setText("Endereço");

        jLabelTipoFunncionario.setText("Tipo de Funcionário");

        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jTFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFEmailActionPerformed(evt);
            }
        });

        jTFDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDataNascActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioAdm);
        jRadioAdm.setText("Funcionário Administrador");
        jRadioAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAdmActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioFinanceiro);
        jRadioFinanceiro.setText("Funcionário Financeiro");
        jRadioFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFinanceiroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioProducao);
        jRadioProducao.setText("FuncionárioProdução");

        buttonGroup1.add(jRadioFuncionario);
        jRadioFuncionario.setText("Funcionário ");

        jButtonGravar.setText("Gravar");
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTipoFunncionario)
                            .addComponent(jLabelEndereco)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFCpf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFDataNasc, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTFEndereco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                                .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabelCpf)
                            .addComponent(JlabelDataNasc)
                            .addComponent(jLabelSenha)
                            .addComponent(jLabelEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioFinanceiro)
                                    .addComponent(jRadioAdm)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jButtonGravar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioProducao)
                                    .addComponent(jRadioFuncionario)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jButtonVoltar)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabelEmail)
                .addGap(11, 11, 11)
                .addComponent(jTFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSenha)
                .addGap(11, 11, 11)
                .addComponent(jTFSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(JlabelDataNasc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelTipoFunncionario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioAdm)
                    .addComponent(jRadioProducao))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioFinanceiro)
                    .addComponent(jRadioFuncionario))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGravar)
                    .addComponent(jButtonVoltar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDataNascActionPerformed

    private void jTFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFEmailActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jRadioAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioAdmActionPerformed

    private void jRadioFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioFinanceiroActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
      Gravar();
       
    }//GEN-LAST:event_jButtonGravarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelDataNasc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTipoFunncionario;
    private javax.swing.JRadioButton jRadioAdm;
    private javax.swing.JRadioButton jRadioFinanceiro;
    private javax.swing.JRadioButton jRadioFuncionario;
    private javax.swing.JRadioButton jRadioProducao;
    private javax.swing.JTextField jTFCpf;
    private javax.swing.JTextField jTFDataNasc;
    private javax.swing.JTextField jTFEmail;
    private javax.swing.JTextField jTFEndereco;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFSenha;
    private javax.swing.JTextField jTFTelefone;
    // End of variables declaration//GEN-END:variables
}
